services:

  backend:
    build:
      context: ./backend
      args:
        INSTALL_DEV: "true"
    container_name: linkedin-backend-dev
    volumes:
      - ./backend:/app
      - ./backend/db:/app/db
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    environment:
      # Flask
      - FLASK_APP=app:app
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000

      # logging instantâneo
      - PYTHONUNBUFFERED=1

      # necessário para debugger conectar no host (linux)
      - PYTHONPATH=/app
    command: poetry run flask run --reload
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: linkedin-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
      - backend
    restart: unless-stopped