"""add resume_language to resume

Revision ID: 48ce6fff2c6a
Revises: d18d1de191d7
Create Date: 2026-03-01 19:31:15.822412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48ce6fff2c6a'
down_revision = 'd18d1de191d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume', sa.Column('resume_language', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume', 'resume_language')
    # ### end Alembic commands ###
