"""added education to resumes

Revision ID: 4a6a716788d6
Revises: a2073fc04587
Create Date: 2026-01-08 14:39:20.958450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a6a716788d6'
down_revision = 'a2073fc04587'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume', sa.Column('education', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume', 'education')
    # ### end Alembic commands ###
