"""add created_at and updated_at to jobs

Revision ID: 626a22a315aa
Revises: 48ce6fff2c6a
Create Date: 2026-03-04 19:02:07.155126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '626a22a315aa'
down_revision = '48ce6fff2c6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('jobs', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'updated_at')
    op.drop_column('jobs', 'created_at')
    # ### end Alembic commands ###
