"""Added job_type and programming_langauges fields

Revision ID: 6c5e9faa9e4c
Revises: dfc1f5497035
Create Date: 2025-07-17 18:52:58.474843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c5e9faa9e4c'
down_revision = 'dfc1f5497035'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('programming_languages', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('programming_languages')
        batch_op.drop_column('job_type')

    # ### end Alembic commands ###
