"""Add responsibilities, qualifications, keywords to jobs

Revision ID: 82690e5e26bc
Revises: b08a2f998bec
Create Date: 2025-07-03 18:22:49.381492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82690e5e26bc'
down_revision = 'b08a2f998bec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('responsibilities', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('qualifications', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('keywords', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('keywords')
        batch_op.drop_column('qualifications')
        batch_op.drop_column('responsibilities')

    # ### end Alembic commands ###
