"""Added summay and project columns

Revision ID: 932373dfa847
Revises: c880687b7ba4
Create Date: 2025-07-22 10:28:19.040727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '932373dfa847'
down_revision = 'c880687b7ba4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('projects', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.drop_column('projects')
        batch_op.drop_column('summary')

    # ### end Alembic commands ###
