"""create application_status field

Revision ID: a2073fc04587
Revises: 1c943a6d163d
Create Date: 2025-12-06 14:54:39.115779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2073fc04587'
down_revision = '1c943a6d163d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('application_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'application_status')
    # ### end Alembic commands ###
