"""Add meta languages and contact_info to resume

Revision ID: a6a14f294a64
Revises: 4a6a716788d6
Create Date: 2026-01-09 10:14:39.275602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6a14f294a64'
down_revision = '4a6a716788d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume', sa.Column('meta', sa.JSON(), nullable=True))
    op.add_column('resume', sa.Column('contact_info', sa.JSON(), nullable=True))
    op.add_column('resume', sa.Column('languages', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume', 'languages')
    op.drop_column('resume', 'contact_info')
    op.drop_column('resume', 'meta')
    # ### end Alembic commands ###
