"""Initial full schema

Revision ID: a8fb55f19551
Revises: 
Create Date: 2025-12-06 12:46:03.492336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8fb55f19551'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('urn', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('urn')
    )
    op.create_table('fetch_curl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('base_url', sa.String(), nullable=True),
    sa.Column('query_id', sa.String(), nullable=True),
    sa.Column('variables_count', sa.Integer(), nullable=True),
    sa.Column('variables_job_collection_slug', sa.String(), nullable=True),
    sa.Column('variables_query_origin', sa.String(), nullable=True),
    sa.Column('variables_start', sa.Integer(), nullable=True),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('headers', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('referer', sa.String(), nullable=True),
    sa.Column('cookies', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('linkedin', sa.String(), nullable=True),
    sa.Column('github', sa.String(), nullable=True),
    sa.Column('portfolio', sa.String(), nullable=True),
    sa.Column('languages', sa.JSON(), nullable=True),
    sa.Column('positive_keywords', sa.JSON(), nullable=True),
    sa.Column('negative_keywords', sa.JSON(), nullable=True),
    sa.Column('education', sa.JSON(), nullable=True),
    sa.Column('email_app_password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('jobs',
    sa.Column('urn', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('workplace_type', sa.String(), nullable=True),
    sa.Column('employment_type', sa.String(), nullable=True),
    sa.Column('posted_on', sa.String(), nullable=True),
    sa.Column('job_url', sa.String(), nullable=True),
    sa.Column('description_full', sa.Text(), nullable=True),
    sa.Column('applicants', sa.Integer(), nullable=True),
    sa.Column('description_snippet', sa.Text(), nullable=True),
    sa.Column('easy_apply', sa.Boolean(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('responsibilities', sa.JSON(), nullable=True),
    sa.Column('qualifications', sa.JSON(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('job_type', sa.String(), nullable=True),
    sa.Column('programming_languages', sa.JSON(), nullable=True),
    sa.Column('has_applied', sa.Boolean(), nullable=True),
    sa.Column('applied_on', sa.DateTime(), nullable=True),
    sa.Column('company_urn', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['company_urn'], ['companies.urn'], ),
    sa.PrimaryKeyConstraint('urn')
    )
    op.create_table('resume',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('hard_skills', sa.JSON(), nullable=True),
    sa.Column('professional_experience', sa.JSON(), nullable=True),
    sa.Column('projects', sa.JSON(), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], name='fk_resume_profile_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resume')
    op.drop_table('jobs')
    op.drop_table('profile')
    op.drop_table('fetch_curl')
    op.drop_table('companies')
    # ### end Alembic commands ###
