"""Initial migration with all models

Revision ID: b08a2f998bec
Revises: 
Create Date: 2025-07-02 15:44:31.021775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b08a2f998bec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('urn', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('urn')
    )
    op.create_table('fetch_curl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('base_url', sa.String(), nullable=True),
    sa.Column('query_id', sa.String(), nullable=True),
    sa.Column('variables_count', sa.Integer(), nullable=True),
    sa.Column('variables_job_collection_slug', sa.String(), nullable=True),
    sa.Column('variables_query_origin', sa.String(), nullable=True),
    sa.Column('variables_start', sa.Integer(), nullable=True),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('headers', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('referer', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('urn', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('workplace_type', sa.String(), nullable=True),
    sa.Column('employment_type', sa.String(), nullable=True),
    sa.Column('posted_on', sa.String(), nullable=True),
    sa.Column('job_url', sa.String(), nullable=True),
    sa.Column('description_full', sa.Text(), nullable=True),
    sa.Column('applicants', sa.Integer(), nullable=True),
    sa.Column('description_snippet', sa.Text(), nullable=True),
    sa.Column('easy_apply', sa.Boolean(), nullable=True),
    sa.Column('company_urn', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['company_urn'], ['companies.urn'], ),
    sa.PrimaryKeyConstraint('urn')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    op.drop_table('fetch_curl')
    op.drop_table('companies')
    # ### end Alembic commands ###
