"""add enrichment fields to jobs

Revision ID: c85c2f4331a3
Revises: d73638ae6e75
Create Date: 2026-02-27 21:40:36.576330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c85c2f4331a3'
down_revision = 'd73638ae6e75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('job_state', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('experience_level', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('employment_status', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('application_closed', sa.Boolean(), nullable=True))
    op.add_column('jobs', sa.Column('expire_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'expire_at')
    op.drop_column('jobs', 'application_closed')
    op.drop_column('jobs', 'employment_status')
    op.drop_column('jobs', 'experience_level')
    op.drop_column('jobs', 'job_state')
    # ### end Alembic commands ###
