"""Created Profile table

Revision ID: c880687b7ba4
Revises: 6c5e9faa9e4c
Create Date: 2025-07-21 14:11:53.354060

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'c880687b7ba4'
down_revision = '6c5e9faa9e4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_resume')
    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_resume_profile_id', 'profile', ['profile_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.drop_constraint('fk_resume_profile_id', type_='foreignkey')
        batch_op.drop_column('profile_id')

    op.create_table('_alembic_tmp_resume',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('hard_skills', sqlite.JSON(), nullable=True),
    sa.Column('professional_experience', sqlite.JSON(), nullable=True),
    sa.Column('education', sqlite.JSON(), nullable=True),
    sa.Column('name', sa.VARCHAR(), server_default=sa.text("'Unnamed Resume'"), nullable=False),
    sa.Column('profile_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], name=op.f('fk_resume_profile_id')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
