"""add_premium_metrics_columns

Revision ID: d18d1de191d7
Revises: c85c2f4331a3
Create Date: 2026-02-28 13:09:55.173370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd18d1de191d7'
down_revision = 'c85c2f4331a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('competition_level', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('applicants_velocity', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('seniority_distribution', sa.JSON(), nullable=True))
    op.add_column('jobs', sa.Column('education_distribution', sa.JSON(), nullable=True))
    op.add_column('jobs', sa.Column('work_remote_allowed', sa.Boolean(), nullable=True))
    op.add_column('jobs', sa.Column('premium_title', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('premium_description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'premium_description')
    op.drop_column('jobs', 'premium_title')
    op.drop_column('jobs', 'work_remote_allowed')
    op.drop_column('jobs', 'education_distribution')
    op.drop_column('jobs', 'seniority_distribution')
    op.drop_column('jobs', 'applicants_velocity')
    op.drop_column('jobs', 'competition_level')
    # ### end Alembic commands ###
