"""cria modelo de connections

Revision ID: d73638ae6e75
Revises: a6a14f294a64
Create Date: 2026-02-24 20:47:18.160885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd73638ae6e75'
down_revision = 'a6a14f294a64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('linkedin_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_url', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('headline', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('connected_time', sa.String(), nullable=True),
    sa.Column('vanity_name', sa.String(), nullable=True),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('experiences', sa.JSON(), nullable=True),
    sa.Column('education', sa.JSON(), nullable=True),
    sa.Column('certifications', sa.JSON(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('is_fully_scraped', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_linkedin_connections_profile_url'), 'linkedin_connections', ['profile_url'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_linkedin_connections_profile_url'), table_name='linkedin_connections')
    op.drop_table('linkedin_connections')
    # ### end Alembic commands ###
