"""Added name field to Resume table

Revision ID: dcdaadcf801e
Revises: 05ad2c16470a
Create Date: 2025-07-13 14:00:41.152937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcdaadcf801e'
down_revision = '05ad2c16470a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False, server_default='Unnamed Resume'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
