"""Added has_applied column do Job table

Revision ID: dfc1f5497035
Revises: dcdaadcf801e
Create Date: 2025-07-15 08:36:35.686208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfc1f5497035'
down_revision = 'dcdaadcf801e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_applied', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('has_applied')

    # ### end Alembic commands ###
