"""Included cookies field to FetchCurl model

Revision ID: e9b7cc8d0c6f
Revises: fafef4e9c8de
Create Date: 2025-08-11 22:24:20.282628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9b7cc8d0c6f'
down_revision = 'fafef4e9c8de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fetch_curl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cookies', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fetch_curl', schema=None) as batch_op:
        batch_op.drop_column('cookies')

    # ### end Alembic commands ###
