"""Added applied_on field

Revision ID: f7a4b640142e
Revises: b6a9bb8f7dd9
Create Date: 2025-08-02 18:30:39.787878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7a4b640142e'
down_revision = 'b6a9bb8f7dd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('applied_on', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('applied_on')

    # ### end Alembic commands ###
