"""add job_urn to emails

Revision ID: f9cd4ef9e4ca
Revises: 626a22a315aa
Create Date: 2026-03-09 14:34:44.713547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9cd4ef9e4ca'
down_revision = '626a22a315aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_emails_job_urn'), 'emails', ['job_urn'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emails_job_urn'), table_name='emails')
    # ### end Alembic commands ###
